/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCertIdRouteImport } from './routes/verify.$certId'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as CorporateDashboardRouteImport } from './routes/corporate.dashboard'
import { Route as CatalogCourseIdRouteImport } from './routes/catalog.$courseId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertIdRoute = VerifyCertIdRouteImport.update({
  id: '/$certId',
  path: '/$certId',
  getParentRoute: () => VerifyRoute,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateDashboardRoute = CorporateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CorporateRoute,
} as any)
const CatalogCourseIdRoute = CatalogCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/corporate': typeof CorporateRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRouteWithChildren
  '/catalog/$courseId': typeof CatalogCourseIdRoute
  '/corporate/dashboard': typeof CorporateDashboardRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/verify/$certId': typeof VerifyCertIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/corporate': typeof CorporateRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRouteWithChildren
  '/catalog/$courseId': typeof CatalogCourseIdRoute
  '/corporate/dashboard': typeof CorporateDashboardRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/verify/$certId': typeof VerifyCertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/corporate': typeof CorporateRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRouteWithChildren
  '/catalog/$courseId': typeof CatalogCourseIdRoute
  '/corporate/dashboard': typeof CorporateDashboardRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/verify/$certId': typeof VerifyCertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/corporate'
    | '/dashboard'
    | '/verify'
    | '/catalog/$courseId'
    | '/corporate/dashboard'
    | '/learn/$courseId'
    | '/verify/$certId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/corporate'
    | '/dashboard'
    | '/verify'
    | '/catalog/$courseId'
    | '/corporate/dashboard'
    | '/learn/$courseId'
    | '/verify/$certId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/corporate'
    | '/dashboard'
    | '/verify'
    | '/catalog/$courseId'
    | '/corporate/dashboard'
    | '/learn/$courseId'
    | '/verify/$certId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  CorporateRoute: typeof CorporateRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  VerifyRoute: typeof VerifyRouteWithChildren
  LearnCourseIdRoute: typeof LearnCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certId': {
      id: '/verify/$certId'
      path: '/$certId'
      fullPath: '/verify/$certId'
      preLoaderRoute: typeof VerifyCertIdRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/dashboard': {
      id: '/corporate/dashboard'
      path: '/dashboard'
      fullPath: '/corporate/dashboard'
      preLoaderRoute: typeof CorporateDashboardRouteImport
      parentRoute: typeof CorporateRoute
    }
    '/catalog/$courseId': {
      id: '/catalog/$courseId'
      path: '/$courseId'
      fullPath: '/catalog/$courseId'
      preLoaderRoute: typeof CatalogCourseIdRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogCourseIdRoute: typeof CatalogCourseIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogCourseIdRoute: CatalogCourseIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface CorporateRouteChildren {
  CorporateDashboardRoute: typeof CorporateDashboardRoute
}

const CorporateRouteChildren: CorporateRouteChildren = {
  CorporateDashboardRoute: CorporateDashboardRoute,
}

const CorporateRouteWithChildren = CorporateRoute._addFileChildren(
  CorporateRouteChildren,
)

interface VerifyRouteChildren {
  VerifyCertIdRoute: typeof VerifyCertIdRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyCertIdRoute: VerifyCertIdRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRouteWithChildren,
  CorporateRoute: CorporateRouteWithChildren,
  DashboardRoute: DashboardRoute,
  VerifyRoute: VerifyRouteWithChildren,
  LearnCourseIdRoute: LearnCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
